version: '3.5'
services:
  node:
    restart: always
    depends_on:
      - mongo
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: