name: Nest.js Jest CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: db
      - run: yarn install --frozen-lockfile
      - run: yarn prebuild
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: yarn test:e2e
